<?php
/* this file is auto generated by coop cz system */
namespace server\lib\model\trader;
class RecordEOSUSDT extends \ar\core\Model
{
    public $tableName = 'record_EOS-USDT';
    public function getDb($dbType = "mysql", $dbString = "trader", $read = true)
            {
                return parent::getDb($dbType, $dbString, $read);
            }
            
}
