<?php
/* this file is auto generated by coop cz system */
namespace server\lib\model\tchecker;
class TcheckerRegistercode extends \ar\core\Model
{
    public $tableName = 'tchecker_registercode';
    public function getDb($dbType = "mysql", $dbString = "tchecker", $read = true)
            {
                return parent::getDb($dbType, $dbString, $read);
            }
            
}
