<?php
/* this file is auto generated by coop cz system */
namespace server\lib\model\tchecker_paint;
class Records extends \ar\core\Model
{
    public $tableName = 'records';
    public function getDb($dbType = "mysql", $dbString = "tchecker_paint", $read = true)
            {
                return parent::getDb($dbType, $dbString, $read);
            }
            
}
